<?php


namespace Dodo\TestGenerator\FileLoader;

use Dodo\TestGenerator\Helper\Sanitizer;
use Symfony\Component\HttpClient\HttpClient;

class JslFileLoader extends FileLoader {

  function loadFile(string $url): array {
    $file = parent::loadFile($url); // TODO: Change the autogenerated stub
    $file = Sanitizer::sanitize($file);
    return $file;
  }
  
}